CREATE DATABASE BBK;
USE BBK;


CREATE TABLE CYCLIST(
	CYCLISTID		INT 		NOT NULL,
    NAME		VARCHAR(10)		NOT NULL,
	MOBILE		BIGINT 			NOT NULL,
    EMAIL		VARCHAR(30)		NOT NULL,
    PRIMARY KEY(CYCLISTID)
);


CREATE TABLE CLASS(
	CLASSID		VARCHAR(10) 	NOT NULL,
    TITLE		VARCHAR(25)		NOT NULL,
    DATE		DATE,
    PRIMARY KEY(CLASSID)
);

CREATE TABLE BIKE(
	BIKEID		INT		NOT NULL,
	MODEL	VARCHAR(10)		NOT NULL,
    MAKE	VARCHAR(20)		NOT NULL,
    CYCLISTID 	INT 	NOT NULL,
    PRIMARY KEY(BIKEID),
    FOREIGN KEY(CYCLISTID) REFERENCES CYCLIST(CYCLISTID)
);

CREATE TABLE REPAIR(
	REPAIRID	INT 	NOT NULL,
    DATE		date	NOT NULL,
    BIKEID 		INT 	NOT NULL,
    PRIMARY KEY(REPAIRID),
    FOREIGN KEY(BIKEID) REFERENCES BIKE(BIKEID)
);

CREATE TABLE FAULT(
	FAULTID		INT 	NOT NULL,
    DESCRIPTION 	VARCHAR(20)		NOT NULL,
    REPAIRID		INT 	NOT NULL,
    PRIMARY KEY(FAULTID),
    FOREIGN KEY(REPAIRID) REFERENCES REPAIR(REPAIRID)
);

CREATE TABLE VOLUNTEER(
	VOLUNTEERID		INT 	NOT NULL,
    MOBILE			INT 	NOT NULL,
    EMAIL		VARCHAR(20)		NOT NULL,
    NAME		VARCHAR(15)		NOT NULL,
    PRIMARY KEY(VOLUNTEERID)
);

CREATE TABLE PART(
	PARTID		INT 		NOT NULL,
    COST		VARCHAR(4)	NOT NULL,
    NAME 		VARCHAR(15)	NOT NULL,
    QUANTITY	VARCHAR(3)	NOT NULL,
    REPAIRID 	INT 	NOT NULL,
    PRIMARY KEY(PARTID),
    FOREIGN KEY(REPAIRID) REFERENCES REPAIR(REPAIRID)
);

CREATE TABLE FAULT_VOLUNTEER(
	FAULTID		INT 	NOT NULL,
    VOLUNTEERID		INT 	NOT NULL,
    DATE 		date		NOT NULL,
    COMMENT		VARCHAR(20)		NOT NULL,
    PRIMARY KEY(FAULTID,VOLUNTEERID)
);

CREATE TABLE CYCLIST_CLASS(
	CYCLISTID	INT		NOT NULL,
    CLASSID		INT 	NOT NULL,
    PRIMARY KEY(CYCLISTID,CLASSID)
);